### ISSUE TITLE
✨ 팔로우 캐시 추가

### ISSUE THREAD

**Issue by niamu01** [42Statistics/42Stat-Backend#413]
## 팔로우, 팔로우 리스트 캐시
1. 최신 cache 보장
2. 데이터 정합성 보장
3. db에 write하는 주기 조절 가능

Read Through, Write Through 방법으로 캐시하기로 결정

### Read Through
(followList)
```
App <-(1)- Cache <-(2)- DB
```
1. Hit: read from cache
2. Read: read from db, store in cache
- 읽기가 많은 워크로드에 적합
- 캐시에 요청하는 방식이라 첫 요청은 fail

### Write Through
(follow/unfollow)
```
App -(1)-> Cache 
    -(2)-> DB
```
1. write to cache
2. write to db
- 데이터 일관성 유지

---

```ts
type FollowLists = {
  followerUser[],
  followingUser[]
}
```
`Map<id, FollowLists>`의 형태로 캐시하다가,

1. follower, following 리스트가 동시에 불리는 일이 없다는 점과
2. 각 리스트의 업데이트 주기가 다르기 때문에

`Map<id:following, followingUser[]>`, `Map<id:follower, followerUser[]>` 으로 변경

---

#### 사용한 데이터
cursusUser의 모든 사람(2553명)이 모두 랜덤한 100명을 팔로우 함
followAt 날짜도 랜덤

#### Artillery
기존에 있던 phases 활용해서 테스트

read: _팔로우 리스트_ 쿼리
```yml
config:
  target: 'http://localhost:4000'
  phases:
    - name: 'Warm up the API'
      duration: 5
      arrivalRate: 5
    - name: Ramp up to peak load
      duration: 5
      arrivalRate: 5
      rampTo: 200
    - name: Sustained peak load
      duration: 120
      rampTo: 200
  payload:
    - path: '../csv/user-ids/id-2553.csv'
      skipHeader: true
      fields:
        - 'targetId'
```
<img width="781" alt="image" src="https://github.com/42Statistics/42Stat-Backend/assets/74657997/f71beb8e-65ad-4f6f-be3d-9fe444f62da0">

```yml
config:
  target: 'http://localhost:4000'
  phases:
    - name: 'Warm up the API'
      duration: 5
      arrivalRate: 5
    - name: Ramp up to peek load
      duration: 5
      arrivalRate: 5
      rampTo: 70
    - name: Sustained peak load
      duration: 120
      rampTo: 70
  payload:
    - path: '../csv/user-ids/id-2553.csv'
      skipHeader: true
      fields:
        - 'targetId'
```
<img width="779" alt="image" src="https://github.com/42Statistics/42Stat-Backend/assets/74657997/1d284868-4369-4564-a6b0-7b5a8639f4a8">

---

근황:
240123 팔로우 캐시 만들다가 로직 바꾸고 있습니다...

최종 반환 타입: 
`{isFollowing, userPreview, followAt}[]`

1. db에 요청: userId, followId 로 follower/following 리스트를 만든 후 userPreview와 followAt 을 추가해 반환
2. cache에 요청: cache하던 {userPreview, followAt}[] 에 로그인 한 유저에 맞춰 isFollowing 추가 후 반환

follow/unfollow시 db, cache에 동시 write (각 타입에 맞게 업데이트 함)

240125 완성 및 Artillery 검사 추가
240128 preload cache로 만들기
240207 preload cache가 있는 상태에서 Artillery로 다시 테스트 (진행중)

### 남은 일
- [x] cache 기간 설정 (0)
- [x] isFollowing 도 cache에서 확인하도록 만들기
- [x] unshift? push 후 sort?
  - sort가 바뀔 수 있다 -> push 후 매번 (마지막에) sort하여 반환
- [x] follow, unfollow처럼 실패시 cache 동작 못하게 막기 (트랜젝션)
  - 현재 db실패시 cache안하게만 해줌
  - 인메모리 캐시라 적용 x
- [x] preload cache와 함께 Artillery 테스트
